---
- name: Create installation directory
  file:
    path: '{{ forgejo_path }}'
    state: directory
    owner: '{{ forgejo_user }}'
    group: '{{ forgejo_group }}'
    mode: 0775
- name: Get forgejo user info
  ansible.builtin.getent:
    database: passwd
    key: '{{ forgejo_user }}'
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ forgejo_path }}/docker-compose.yml'
    owner: '{{ forgejo_user }}'
    group: '{{ forgejo_group }}'
    mode: 0664
  vars:
    forgejo_user_id: '{{ ansible_facts.getent_passwd[forgejo_user][1] }}'
    forgejo_group_id: '{{ ansible_facts.getent_passwd[forgejo_group][1] }}'
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ forgejo_path }}'
    user: root
    hour: 4
    minute: 30
    job: 'docker compose -f {{ forgejo_path }}/docker-compose.yml down && docker compose -f {{ forgejo_path }}/docker-compose.yml pull && docker compose -f {{ forgejo_path }}/docker-compose.yml up -d'
- name: Copy backup_forgejo.sh
  ansible.builtin.template:
    src: backup_forgejo.sh.j2
    dest: '{{ forgejo_path }}/backup_forgejo.sh'
    owner: root
    group: root
    mode: 0775
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ forgejo_path }}'
    user: root
    hour: 1
    minute: 0
    job: '{{ forgejo_path }}/backup_forgejo.sh'
